# This is an example of how to provide a templated application properties file to an application running in kubernetes.
# This block will read in 'files/application.properties' and create a configmap which can be mounted to a pod.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-agent-env
data:
  DD_SITE: "datadoghq.com"
  DD_HOSTNAME: {{ .Chart.Name }}-solace-trials
  DD_API_KEY: {{ .Values.datadog.apiKey }}
  DD_TAGS: {{ .Values.datadog.appKey }}
  DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
