# This is an example of how to provide a templated application properties file to an application running in kubernetes.
# This block will read in 'files/application.properties' and create a configmap which can be mounted to a pod.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-agent-env
data:
  {{ (tpl (.Files.Glob "agent.env.tpl").AsConfig . ) | indent 2 }}%