apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ template "solace-trial-brokers-monitoring.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  access_key_id: {{ .Values.accessKeyId | b64enc | quote }}
  secret_access_key: {{ .Values.secretAccessKey | b64enc | quote }}
