# This is an example of how to provide a templated application properties file to an application running in kubernetes.
# This block will read in 'files/application.properties' and create a configmap which can be mounted to a pod.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-solace-trials-yaml
data:
  solace_trials.yaml: |-
    init_config:

    instances:
      - host: {{ .Chart.Name }}-solace-trials
        min_collection_interval: 600
        maas_api_url: https://{{ .Values.maas.maas_prefix }}-api.{{ .Values.maas.maas_domain }}/api
        ops_console_user: {{ .Values.maas.operator_username }}
        ops_console_password: {{ .Values.maas.operator_password }}
        semp_timeout: 10