name: Create Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      githubRelease:
        type: boolean
        required: true
        default: true
        description: Create github release
      version:
        description: "Version to release"
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"


      - name: create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.event.inputs.version }}"
          message: "Release ${{ github.event.inputs.version }}"

      - name: "Generate Changelog"
        id: Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignorePreReleases: "true"
          fromTag: ${{ steps.last_release.outputs.tag_name }}
          toTag: ${{ github.event.inputs.version }}


      - name: Change log generator
        run: |
          echo "release notes are: ${{ steps.Changelog.outputs.changelog }}"

      - name: Create Release
        if: github.event.inputs.githubRelease
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false